name: m3u8-daily-task

on:
  
  push: # push触发
    branches: [ master ]
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '10 6 * * *' # cron表达式，Actions时区是UTC时间，所以要往前推8个小时,如上表示每天14点10分
    
jobs:
  run-get-m3u8-list:

    runs-on: ubuntu-latest
    
    steps:
    # 检出
    - name: Checkout
      uses: actions/checkout@v2
      
    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
    # .Net Core 环境
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    # 安装依赖
    - name: Install dependencies
      run: dotnet restore
      
    # 构建应用
    - name: Build
      run: dotnet build --configuration Release --no-restore
       
    # 运行
    - name: Run
      run: dotnet run getM3U8.dll
      
    # update docs
    - name: Commit to gh-pages and push
      run: |
          $ErrorActionPreference = "Continue"
          git add -A
          git diff HEAD --exit-code
          if ($LASTEXITCODE -eq 0) {
            Write-Host "No changes to commit!"
          } else {
            git config --global user.name "mayaxcn"
            git config --global user.email "mayax@vip.qq.com"
            git commit -m "Updated M3U8 list"
            git remote set-url origin https://x-access-token:${{ secrets.M3U8_GIT_KEY }}@github.com/getM3U8
            git add README.md
          }
